import React from 'react'
import Helmet from 'react-helmet'
import { Home as Index } from '@styles/pages'
import { useAppSelector } from '@lib/hooks'
import { users } from '@store/slices/users'
import { Layout, PageHeader, Button, Table } from 'antd'

const { Content } = Layout

type TableColumn = {
	title: string
	dataIndex: string
	key: string
	render?(arg: string): React.ReactNode
}

const HomePage: React.FC = () => {
	// const dispatch = useAppDispatch()
	const userList = useAppSelector((state) => {
		const user = state.users.user
		return user ?? []
	})
	const [columns] = React.useState<TableColumn[]>([
		{ title: 'id', dataIndex: 'id', key: 'id' },
		{ title: 'title', dataIndex: 'title', key: 'title' },
		{ title: 'client', dataIndex: 'client', key: 'client' },
		{ title: 'area', dataIndex: 'area', key: 'area' },
		{ title: 'country', dataIndex: 'country', key: 'country' },
		{
			title: 'contact',
			dataIndex: 'contact',
			key: 'contact',
			render: (contact: string) => {
				return <a href="javascript;">{contact}</a>
			},
		},
		{ title: 'assignee', dataIndex: 'assignee', key: 'assignee' },
	])

	const getUser = async () => {
		console.log(users())
		// await dispatch(users())
	}

	return (
		<Index>
			<Helmet>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Helmet>
			<PageHeader className="page-header" title="Index" subTitle="This is main page" />
			<Content className="site-layout-content">
				<Button type="primary" onClick={getUser}>
					회원 정보 불러오기
				</Button>
				<Table dataSource={userList} columns={columns} />
			</Content>
		</Index>
	)
}

export default HomePage
